version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
init:
- cmd: SET PATH=C:\Python38;C:\Python38\Scripts;%PATH%
install:
- cmd: sh setup.sh
build_script:
- ps: >-
    sh notifier.sh

    $fileName = $pwd.Path + "/diff.txt"

    if ( !(Test-Path $fileName)) {
        exit 1
    }

    if ($LastExitCode -eq 0) {
        $file = New-Object System.IO.StreamReader($fileName)
        $message = ""
        while (($line = $file.ReadLine()) -ne $null)
        {
            Write-Host $line
            $message += $line + "\n"
        }
        Add-AppveyorMessage -Message $message
    } else {
        Add-AppveyorMessage -Message "Nothing"
        Push-AppveyorArtifact "wandbox-compilers.txt" -DeploymentName "wandbox-compilers"
    }
test: off
artifacts:
- path: wandbox-compilers.txt
  name: wandbox-compilers
deploy: off
#notifications:
#- provider: Webhook
#  url:
#    secure: GswYBbi5QpxlJBk8YiJ5vHC3vhAJ60aQrUpzXSJ1EkQU3ZCbJL0BDTxRk/xtZFUMtdBwwCYn8XehCjSQS7ciGQ==
#  method: POST
#  body: >-
#    {
#        "buildUrl": [ "{{buildUrl}}" ],
#        "buildNumber": {{buildNumber}},
#        "buildVersion": "{{buildVersion}}",
#        "message": [
#        {{#jobs}}
#            {{#messages}}
#            "{{message}}",
#            {{/messages}}
#        {{/jobs}}
#            ""
#        ]
#    }
#  on_build_success: true
#  on_build_failure: false
#  on_build_status_changed: false
