name: Wandbox News
on: [push]

env:
  LISTFILE: wandbox-compilers.txt
  LASTFILE: last.txt
  DIFFFILE: diff.txt

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup
        run: ./setup.sh
      - name: current
        run: python wandbox-listup-compiler.py > $LISTFILE
      - name: download-lastfile
        run: echo .
      - name: diff
        run: python wandbox-compilerlist-diff.py $LASTFILE $LISTFILE > $DIFFFILE
      - name: result
        run: cat $LISTFILE
